name: diphtoscan
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython
  - pandas
  - pip
  - requests
  - setuptools
  - blast
  - hmmer
  - mash
  - ncbi-amrfinderplus >=3,<5
  - jolytree
  - integron_finder



