name: diphtoscan
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pandas
  - ncbi-amrfinderplus >=3,<5
  - mash
  - hmmer
  - blast
  - requests
  - biopython
  - jolytree
  - integron_finder



